name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev libncurses5-dev libelf-dev clang lld git

      - name: Download Toolchain
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

      - name: Build Kernel
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          make O=out ARCH=arm64 vendor/caprip_defconfig
          make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android-

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Overclocked-Kernel
          path: out/arch/arm64/boot/Image.gz-dtb
